export type Palette = {
  '50': string;
  '100': string;
  '200': string;
  '300': string;
  '400': string;
  '500': string;
  '600': string;
  '700': string;
  '800': string;
  '900': string;
  // bg: string;
  // surface: string;
  // surfaceAlt: string;
  // border: string;
  // text: string;
  // textMuted: string;
  // accent: string;
  // accentHover: string;
  // accentActive: string;
  // hover: string;
  // active: string;
  // focus: string;
  base: string;
};
